"""
Django settings for libraryproject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-_wl5!@d9ytu1^cbf+ig--4g#jmao02ryb6+n(83-_&057@s5u9'
# !! IMPORTANT !!
# Set the SECRET_KEY environment variable in your hosting environment.
# Do not commit your secret key to version control.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    # Provide a default for local development if needed, but this should fail in production if not set
    print("WARNING: SECRET_KEY environment variable not set. Using a default (insecure) key for local development.")
    SECRET_KEY = 'local-insecure-default-key-change-me' # Replace with a default for local dev if you like, or raise an error

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # Set to False for production

# !! IMPORTANT !! Change ['*'] to your actual domain(s) on PythonAnywhere/hosting provider
# Example: ALLOWED_HOSTS = ['your-username.pythonanywhere.com']
ALLOWED_HOSTS = ['gods0ft.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'library.apps.LibraryConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_select2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Add WhiteNoiseMiddleware right after SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'libraryproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'libraryproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# !! IMPORTANT !!
# The following database settings are for local development.
# You MUST configure the database settings in your hosting environment (e.g., PythonAnywhere).
# Typically, this involves setting environment variables (e.g., DATABASE_URL)
# or using the hosting provider's database service configuration tools.
# Commenting out the local config to avoid accidental use in production.

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'library_db',
#         'USER': 'root',
#         'PASSWORD': '2205', # Consider using env variable even locally
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset': 'utf8mb4',
#         },
#     }
# }

# Example for using dj-database-url (install it: pip install dj-database-url)
# Needs environment variable DATABASE_URL set in production
import dj_database_url
DATABASES = {
    # dj_database_url будет искать переменную окружения DATABASE_URL
    'default': dj_database_url.config()
}
# # Add your actual production DATABASE_URL from PythonAnywhere/Heroku/etc.
# # DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True) # Example for Heroku Postgres


# Tells Django to use our custom user model
AUTH_USER_MODEL = 'library.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directory where collectstatic will gather static files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional directories Django should search for static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Add WhiteNoise storage backend
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect after login to the home_redirect view
LOGIN_REDIRECT_URL = 'home'

# Redirect after logout to the login page
LOGOUT_REDIRECT_URL = 'login'